const Sites = [{
    id: 1,
    name: "Devinterest Front",
    link: "https://devinterest.surge.sh/",
    image: "/images/Devinterest.png",
    description: "Ceci est mon premier site, projet de fin de formation de l'école O'clock, le site s'appelle Dev Interest.",
    technos: ["react","sass"],
    type: "front",
    libs: ["dotenv-flow","cssnano","resolve-url-loader","axios","bootstrap-icons","redux","react-redux"],
    detail: "description détaillée",
    color: "#14C852",
    online: true,

},
{
    id: 2,
    name: "Devinterest Back",
    link: "https://devinterest.herokuapp.com/cards",
    image: "/images/devinterest-back.png",
    description: "Api heberger sur heroku pour le fonctionnement du site Front : Devinterest",
    technos: ["nodejs","css","postgresql"],
    type: "back",
    libs: ["JWT","@hapi/joi","bcrypt","cors","dotenv","express","jsonwebtoken","pg","sanitizer"],
    detail: "description détaillée",
    color: "#14C852",
    online: true,
},
{
    id: 3,
    name: "Portfolio 1 test",
    link: "https://frederic-b.herokuapp.com/",
    image: "/images/portfolio1.png",
    description: "ceci est un portfolio, site créer pour m'entrainer.",
    technos: ["nodejs","css"],
    type: "front",
    libs: [""],
    detail: "description détaillée",
    color: "#14C852",
    online: true,
},
{
    id: 4,
    name: "Mon portfolio",
    link: "https://portfolio-fb.surge.sh/",
    image: "/images/portfolio2.png",
    description: "ceci est mon portfolio, encore quelques améliorations à faire !, site fonctionnel heberger sur surge.sh (build).",
    technos: ["react","sass"],
    type: "front",
    libs: ["react-cookie-consent","swiper","typewriter-effect"],
    detail: "description détaillée",
    color: "#14C852",
    online: true,
},
{
    id: 5,
    name: "Prochainement",
    link: "",
    image: "images/nothing.jpg",
    description: "Bientôt ici un site !",
    technos: ["react","sass"],
    type: "front",
    libs: [""],
    detail: "description détaillée",
    color: "crimson",
    online: false,
},
{
    id: 6,
    name: "Prochainement",
    link: "",
    image: "images/nothing.jpg",
    description: "Bientôt ici un site !",
    technos: ["react","sass"],
    type: "front",
    libs: [""],
    detail: "description détaillée",
    color: "crimson",
    online: false,
},
]

export default Sites